# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: backtest.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'backtest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62\x61\x63ktest.proto\x12\x08\x62\x61\x63ktest\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x01\n\x14StartBacktestRequest\x12\x10\n\x08model_id\x18\x01 \x01(\x03\x12)\n\x05\x66rom_\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12&\n\x02to\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x0finitial_balance\x18\x04 \x01(\x01\",\n\x15StartBacktestResponse\x12\x13\n\x0b\x62\x61\x63ktest_id\x18\x01 \x01(\x03\"E\n\x19GetBacktestStatusResponse\x12(\n\x06status\x18\x01 \x01(\x0e\x32\x18.backtest.BacktestStatus\"/\n\x18GetBacktestStatusRequest\x12\x13\n\x0b\x62\x61\x63ktest_id\x18\x01 \x01(\x03*\x9d\x01\n\x0e\x42\x61\x63ktestStatus\x12\x1a\n\x16\x42\x61\x63ktestStatus_Unknown\x10\x00\x12\x1a\n\x16\x42\x61\x63ktestStatus_Pending\x10\x01\x12\x1a\n\x16\x42\x61\x63ktestStatus_Running\x10\x02\x12\x1c\n\x18\x42\x61\x63ktestStatus_Completed\x10\x03\x12\x19\n\x15\x42\x61\x63ktestStatus_Failed\x10\x04\x32\xc5\x01\n\x0f\x42\x61\x63ktestService\x12R\n\rStartBacktest\x12\x1e.backtest.StartBacktestRequest\x1a\x1f.backtest.StartBacktestResponse\"\x00\x12^\n\x11GetBacktestStatus\x12\".backtest.GetBacktestStatusRequest\x1a#.backtest.GetBacktestStatusResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backtest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BACKTESTSTATUS']._serialized_start=379
  _globals['_BACKTESTSTATUS']._serialized_end=536
  _globals['_STARTBACKTESTREQUEST']._serialized_start=62
  _globals['_STARTBACKTESTREQUEST']._serialized_end=210
  _globals['_STARTBACKTESTRESPONSE']._serialized_start=212
  _globals['_STARTBACKTESTRESPONSE']._serialized_end=256
  _globals['_GETBACKTESTSTATUSRESPONSE']._serialized_start=258
  _globals['_GETBACKTESTSTATUSRESPONSE']._serialized_end=327
  _globals['_GETBACKTESTSTATUSREQUEST']._serialized_start=329
  _globals['_GETBACKTESTSTATUSREQUEST']._serialized_end=376
  _globals['_BACKTESTSERVICE']._serialized_start=539
  _globals['_BACKTESTSERVICE']._serialized_end=736
# @@protoc_insertion_point(module_scope)
