# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.proto import backtest_pb2 as backtest__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in backtest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BacktestServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartBacktest = channel.unary_unary(
                '/backtest.BacktestService/StartBacktest',
                request_serializer=backtest__pb2.StartBacktestRequest.SerializeToString,
                response_deserializer=backtest__pb2.StartBacktestResponse.FromString,
                _registered_method=True)
        self.GetBacktestStatus = channel.unary_unary(
                '/backtest.BacktestService/GetBacktestStatus',
                request_serializer=backtest__pb2.GetBacktestStatusRequest.SerializeToString,
                response_deserializer=backtest__pb2.GetBacktestStatusResponse.FromString,
                _registered_method=True)
        self.GetBacktest = channel.unary_unary(
                '/backtest.BacktestService/GetBacktest',
                request_serializer=backtest__pb2.GetBacktestRequest.SerializeToString,
                response_deserializer=backtest__pb2.BacktestInfo.FromString,
                _registered_method=True)
        self.CancelBacktest = channel.unary_unary(
                '/backtest.BacktestService/CancelBacktest',
                request_serializer=backtest__pb2.CancelBacktestRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetAllUserBacktests = channel.unary_unary(
                '/backtest.BacktestService/GetAllUserBacktests',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=backtest__pb2.GetAllUserBacktestsResponse.FromString,
                _registered_method=True)


class BacktestServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartBacktest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBacktestStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBacktest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelBacktest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllUserBacktests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BacktestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.StartBacktest,
                    request_deserializer=backtest__pb2.StartBacktestRequest.FromString,
                    response_serializer=backtest__pb2.StartBacktestResponse.SerializeToString,
            ),
            'GetBacktestStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBacktestStatus,
                    request_deserializer=backtest__pb2.GetBacktestStatusRequest.FromString,
                    response_serializer=backtest__pb2.GetBacktestStatusResponse.SerializeToString,
            ),
            'GetBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBacktest,
                    request_deserializer=backtest__pb2.GetBacktestRequest.FromString,
                    response_serializer=backtest__pb2.BacktestInfo.SerializeToString,
            ),
            'CancelBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelBacktest,
                    request_deserializer=backtest__pb2.CancelBacktestRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetAllUserBacktests': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllUserBacktests,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=backtest__pb2.GetAllUserBacktestsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'backtest.BacktestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('backtest.BacktestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BacktestService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/backtest.BacktestService/StartBacktest',
            backtest__pb2.StartBacktestRequest.SerializeToString,
            backtest__pb2.StartBacktestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBacktestStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/backtest.BacktestService/GetBacktestStatus',
            backtest__pb2.GetBacktestStatusRequest.SerializeToString,
            backtest__pb2.GetBacktestStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/backtest.BacktestService/GetBacktest',
            backtest__pb2.GetBacktestRequest.SerializeToString,
            backtest__pb2.BacktestInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/backtest.BacktestService/CancelBacktest',
            backtest__pb2.CancelBacktestRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllUserBacktests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/backtest.BacktestService/GetAllUserBacktests',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            backtest__pb2.GetAllUserBacktestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
