syntax = "proto3";

package backtest;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

service BacktestService {
  rpc StartBacktest(StartBacktestRequest) returns (StartBacktestResponse) {}
  rpc GetBacktestStatus(GetBacktestStatusRequest) returns (GetBacktestStatusResponse) {}
  rpc GetBacktest(GetBacktestRequest) returns (BacktestInfo) {}
  rpc CancelBacktest(CancelBacktestRequest) returns (google.protobuf.Empty) {}
  rpc GetAllUserBacktests(google.protobuf.Empty) returns (GetAllUserBacktestsResponse) {}
}

message CancelBacktestRequest {
  int64 backtest_id = 1;
}

message GetBacktestRequest {
  int64 backtest_id = 1;
}

message UserInfo {
  int64 id = 1;
  string email = 2;
}

message BacktestInfo {
  int64 backtest_id = 1;
  UserInfo user_info = 2;
  google.protobuf.Timestamp started_at = 3;
  google.protobuf.Timestamp finished_at = 4;
  google.protobuf.Timestamp test_period_start = 5;
  google.protobuf.Timestamp test_period_end = 6;
  BacktestStatus status = 7;
  double profit = 8;
  int32 trades_count = 9;
  double initial_balance = 10;
  double final_balance = 11;
  google.protobuf.Timestamp created_at = 12;
  ShortModelInfo model_info = 13;
}

message GetAllUserBacktestsResponse {
  repeated BacktestInfo backtests = 1;
}

message StartBacktestRequest {
  int64 model_id = 1;
  google.protobuf.Timestamp from_ = 2;
  google.protobuf.Timestamp to = 3;
  double initial_balance = 4;
}

message StartBacktestResponse {
  int64 backtest_id = 1;
}

enum BacktestStatus {
  BacktestStatus_Unknown = 0;
  BacktestStatus_Pending = 1;
  BacktestStatus_Running = 2;
  BacktestStatus_Completed = 3;
  BacktestStatus_Failed = 4;
  BacktestStatus_Cancelled = 5;
}

message GetBacktestStatusResponse {
  BacktestStatus status = 1;
}

message GetBacktestStatusRequest {
  int64 backtest_id = 1;
}

message ShortModelInfo {
  int64 id = 1;
  string instrument_id = 2;
  string name = 3;
  string type = 4;
  google.protobuf.Timestamp created_at = 5;
}
