syntax = "proto3";

package invest;

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";
import "google/protobuf/timestamp.proto";

service InvestService {
  rpc GetSupportedInstruments(google.protobuf.Empty) returns (GetSupportedInstrumentsResponse) {}
  rpc GetInstrumentStat(GetInstrumentStatRequest) returns (GetInstrumentStatResponse) {}
  rpc GetCandles(GetCandlesRequest) returns (GetCandlesResponse) {}
}


message GetCandlesRequest {
  string instrument_id = 1;
  google.protobuf.Timestamp from = 2;
  google.protobuf.Timestamp to = 3;
}

message GetCandlesResponse {
  repeated Candle candles = 1;
}

message Candle {
  google.protobuf.Timestamp timestamp = 1;
  float open = 2;
  float high = 3;
  float low = 4;
  float close = 5;
}

message GetInstrumentStatRequest {
  string instrument_id = 1;
  StatType stat_type = 2;
  google.protobuf.Timestamp from = 3; // defaults to now() - 5 min
  google.protobuf.Timestamp to = 4;   // defaults to now()
}

message GetInstrumentStatResponse {
  double stat_value = 1;
}

message GetSupportedInstrumentsResponse {
  repeated InstrumentInfo instruments = 1;
}

message InstrumentInfo {
  string id = 1;
  google.protobuf.StringValue figi = 2;
  string name = 3;
  int32 lot = 4;
  string currency = 5;
  string sector = 6;
  bool buy_available = 7;
  bool sell_available = 8;
}

enum StatType {
    StatType_Unknown = 0;
    StatType_BollingerBandLower = 1;
    StatType_BollingerBandMiddle = 2;
    StatType_BollingerBandUpper = 3;
    StatType_ExponentialMovingAverage = 4;
    StatType_RelativeStrengthIndex = 5;
    StatType_MovingAverageConvergenceDivergence = 6;
    StatType_MovingAverage = 7;
}

