# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x05model\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"=\n\x14GetAllModelsResponse\x12%\n\x06models\x18\x01 \x03(\x0b\x32\x15.model.ShortModelInfo\"\x7f\n\x0eShortModelInfo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x15\n\rinstrument_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2U\n\x0cModelService\x12\x45\n\x0cGetAllModels\x12\x16.google.protobuf.Empty\x1a\x1b.model.GetAllModelsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETALLMODELSRESPONSE']._serialized_start=84
  _globals['_GETALLMODELSRESPONSE']._serialized_end=145
  _globals['_SHORTMODELINFO']._serialized_start=147
  _globals['_SHORTMODELINFO']._serialized_end=274
  _globals['_MODELSERVICE']._serialized_start=276
  _globals['_MODELSERVICE']._serialized_end=361
# @@protoc_insertion_point(module_scope)
