# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x05model\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\",\n\x14StopExecutionRequest\x12\x14\n\x0c\x65xecution_id\x18\x01 \x01(\x03\"1\n\x19GetExecutionStatusRequest\x12\x14\n\x0c\x65xecution_id\x18\x01 \x01(\x03\"D\n\x1aGetExecutionStatusResponse\x12&\n\x06status\x18\x01 \x01(\x0e\x32\x16.model.ExecutionStatus\"j\n\x15StartExecutionRequest\x12\x10\n\x08model_id\x18\x01 \x01(\x03\x12\x17\n\x0finitial_balance\x18\x02 \x01(\x01\x12&\n\x1emax_execution_duration_seconds\x18\x03 \x01(\x05\".\n\x16StartExecutionResponse\x12\x14\n\x0c\x65xecution_id\x18\x01 \x01(\x03\"=\n\x14GetAllModelsResponse\x12%\n\x06models\x18\x01 \x03(\x0b\x32\x15.model.ShortModelInfo\"\x7f\n\x0eShortModelInfo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x15\n\rinstrument_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*\xa3\x01\n\x0f\x45xecutionStatus\x12\x1b\n\x17\x45xecutionStatus_Unknown\x10\x00\x12\x1b\n\x17\x45xecutionStatus_Pending\x10\x01\x12\x1b\n\x17\x45xecutionStatus_Running\x10\x02\x12\x1a\n\x16\x45xecutionStatus_Failed\x10\x03\x12\x1d\n\x19\x45xecutionStatus_Completed\x10\x04\x32\xcb\x02\n\x0cModelService\x12\x45\n\x0cGetAllModels\x12\x16.google.protobuf.Empty\x1a\x1b.model.GetAllModelsResponse\"\x00\x12O\n\x0eStartExecution\x12\x1c.model.StartExecutionRequest\x1a\x1d.model.StartExecutionResponse\"\x00\x12\x46\n\rStopExecution\x12\x1b.model.StopExecutionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12[\n\x12GetExecutionStatus\x12 .model.GetExecutionStatusRequest\x1a!.model.GetExecutionStatusResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTIONSTATUS']._serialized_start=600
  _globals['_EXECUTIONSTATUS']._serialized_end=763
  _globals['_STOPEXECUTIONREQUEST']._serialized_start=84
  _globals['_STOPEXECUTIONREQUEST']._serialized_end=128
  _globals['_GETEXECUTIONSTATUSREQUEST']._serialized_start=130
  _globals['_GETEXECUTIONSTATUSREQUEST']._serialized_end=179
  _globals['_GETEXECUTIONSTATUSRESPONSE']._serialized_start=181
  _globals['_GETEXECUTIONSTATUSRESPONSE']._serialized_end=249
  _globals['_STARTEXECUTIONREQUEST']._serialized_start=251
  _globals['_STARTEXECUTIONREQUEST']._serialized_end=357
  _globals['_STARTEXECUTIONRESPONSE']._serialized_start=359
  _globals['_STARTEXECUTIONRESPONSE']._serialized_end=405
  _globals['_GETALLMODELSRESPONSE']._serialized_start=407
  _globals['_GETALLMODELSRESPONSE']._serialized_end=468
  _globals['_SHORTMODELINFO']._serialized_start=470
  _globals['_SHORTMODELINFO']._serialized_end=597
  _globals['_MODELSERVICE']._serialized_start=766
  _globals['_MODELSERVICE']._serialized_end=1097
# @@protoc_insertion_point(module_scope)
