# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\":\n\x13GetAccountsResponse\x12#\n\x08\x61\x63\x63ounts\x18\x01 \x03(\x0b\x32\x11.user.AccountInfo\"\x1b\n\x0b\x41\x63\x63ountInfo\x12\x0c\n\x04name\x18\x01 \x01(\t2O\n\x0bUserService\x12@\n\x0bGetAccounts\x12\x16.google.protobuf.Empty\x1a\x19.user.GetAccountsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETACCOUNTSRESPONSE']._serialized_start=49
  _globals['_GETACCOUNTSRESPONSE']._serialized_end=107
  _globals['_ACCOUNTINFO']._serialized_start=109
  _globals['_ACCOUNTINFO']._serialized_end=136
  _globals['_USERSERVICE']._serialized_start=138
  _globals['_USERSERVICE']._serialized_end=217
# @@protoc_insertion_point(module_scope)
