# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"A\n\x12GetAccountsRequest\x12+\n\x0e\x61\x63\x63ount_status\x18\x01 \x01(\x0e\x32\x13.user.AccountStatus\":\n\x13GetAccountsResponse\x12#\n\x08\x61\x63\x63ounts\x18\x01 \x03(\x0b\x32\x11.user.AccountInfo\"\'\n\x0b\x41\x63\x63ountInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t*\x93\x01\n\rAccountStatus\x12\x1e\n\x1a\x41\x43\x43OUNT_STATUS_UNSPECIFIED\x10\x00\x12\x16\n\x12\x41\x43\x43OUNT_STATUS_NEW\x10\x01\x12\x17\n\x13\x41\x43\x43OUNT_STATUS_OPEN\x10\x02\x12\x19\n\x15\x41\x43\x43OUNT_STATUS_CLOSED\x10\x03\x12\x16\n\x12\x41\x43\x43OUNT_STATUS_ALL\x10\x04\x32Q\n\x0bUserService\x12\x42\n\x0bGetAccounts\x12\x18.user.GetAccountsRequest\x1a\x19.user.GetAccountsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNTSTATUS']._serialized_start=189
  _globals['_ACCOUNTSTATUS']._serialized_end=336
  _globals['_GETACCOUNTSREQUEST']._serialized_start=20
  _globals['_GETACCOUNTSREQUEST']._serialized_end=85
  _globals['_GETACCOUNTSRESPONSE']._serialized_start=87
  _globals['_GETACCOUNTSRESPONSE']._serialized_end=145
  _globals['_ACCOUNTINFO']._serialized_start=147
  _globals['_ACCOUNTINFO']._serialized_end=186
  _globals['_USERSERVICE']._serialized_start=338
  _globals['_USERSERVICE']._serialized_end=419
# @@protoc_insertion_point(module_scope)
